### ISSUE TITLE
Chinmay R_Week01_Personal documentation / team meeting

### ISSUE THREAD

**Issue by ChinmayR5** [VIP-SMUR/24Fa-Microclimate-UMCF#14]
### **Overview**
- Week Span: [08-26-2024] to [09-1-2024]

### **Tasks for this week:**

- [ ] Understand OpenFOAM process
- [ ] Understand about OpenFOAM input and output file format.
- [ ] Learn about the Vegetation parameters
- [ ] Start the gather existing research information on the topic

### **Tasks**

- Read the OpenFOAM documentation https://www.openfoam.com/documentation/user-guide
- Read about the OpenFOAM documentation for input and output: https://www.openfoam.com/documentation/user-guide/2-openfoam-cases/2-2-basic-inputoutput-file-format
- Reviewed the Vegetation parameter file
- Started reading research papers, specifically related to the UrbanMicroclimate FOAM and Author Aytac Kubilay

### **Takeaways**

- The OpenFOAM documentation helped me understand the fundamental process of the modeling. 
- The inputs and outputs for the grasshopper tool for Vegetation parameter gave the scope of the detail the solver will capture for the simulation.
- Started learning a new way to perform advanced CFD simulations through OpenFOAM.

### **Team Meetings**

- We defined weekly meetings on Wednesday at 2 PM. (Subject to change)
- Discussed about the above tasks and the way forward

### **Next Week TO-Do's**

- Outline your primary goals and tasks for the next week
