### ISSUE TITLE
Chinmay R_Week02_Personal documentation

### ISSUE THREAD

**Issue by ChinmayR5** [VIP-SMUR/24Fa-Microclimate-UMCF#15]
### **Overview**

- Week : [09-02-2024] to [09-08-2024]

### **Tasks for the week**

- [ ] Plan out the timeline for the semester
- [ ] Write the first draft of research outline.
- [ ] Document the findings on the influence of vegetation cooling as per existing research
- [ ] Document the vegetation parameters learned through any research study

### **Tasks**
- Timeline of the semester is ready. (Tentative)
- 1st draft of the research is done and showed on weekly meetings with Patrick on Friday.
-  Started learning about the parameters and its impact on the cooling potential, such as LAD and Stomatal resistance.
- Started learning and documented the values related a couple of parameters. 
- All the above was presented to the team and Patrick on our weekly Friday meeting

### **Takeaways**

- It was good to plan out the semester as it gave the perspective of the work that is to be completed and organization required for it. writing the first draft about the research outline was beneficial to limit the scope and stay focused on the topic. I also got to learn new parameters related to vegetation which affects the cooling of the microclimate. I found this a good blend of understanding the natural process through advanced computing techniques.

### **Team Meetings**

- I presented my understanding of the OpenFOAM process and vegetation parameters through existing research study. I planned my further tasks and showcased overall updates on the literature review advancements.

### **Next week To-Do's**

- Dive deep into the literature review
- Learn more about the parameters and its effect on the cooling process.
