### ISSUE TITLE
Chinmay R_Week03_Personal documentation

### ISSUE THREAD

**Issue by ChinmayR5** [VIP-SMUR/24Fa-Microclimate-UMCF#16]
## **Weekly Notebook Entry — Week 2**

**Overview**

- Week : [09-09-2024] to [09-16-2024]

**Tasks for the week**

- [ ]  Revise the timeline for the semester
- [ ]  Write the first draft of research Questions.
- [ ]  Document the findings on the influence of vegetation cooling as per existing research

**Tasks**

- Time has been revised as per new knowledge learned about the topic. 
- I have formulated 5-6 research questions highlighting 2 of the most important ones. 
- Conducted more work on the literature review and overall understanding of cooling process through vegetation in general.

**Takeaways**

- The process of learning about the vegetation cooling potential taught me more about the physics behind the temperature regulation through leaves. This has also helped me formulate more high level research questions for the comprehensive study. 

**Team Meetings**

- I presented my new research questions and notes taken on the vegetation parameters, I also presented detail understanding of the individual variables which are used as inputs in the solver.

Next week To-Do's

- Explore the input parameters for Vegetation properties component in the grasshopper tool. 
- At least try and find information on 3-4 parameters.
