### ISSUE TITLE
Week 2_Personal documentation and team meetings_Marcelo Alvarez

### ISSUE THREAD

**Issue by alvarezdmarch** [VIP-SMUR/24Fa-Microclimate-UMCF#2]
### Overview

- **Week Span:** `[09-02-2024]` to `[09-08-2024]`
### Tasks for This Week

- [x]  Task 1: Study the owner.txt and cellZones.txt files
- [x]  Task 2: Develop a custom Grasshopper component to read and group mesh faces in cells. 
- [x] Task 3: Keep track of team's current advances and documentation for the course.
##### Task: [Review constant folder] - _(in progress)_

- **Description:** Study and understand the structure of the files and data inside the constant folder prior to simulation. The main focus is to read and visualize mesh as cells grouped by cellZones.
- **Link to Work:** [https://github.com/gvegasol/UMCF/blob/devMarcelo/Marcelo/MeshFromTxt.cs]()
- **Outcome & Reflection:** The owner.txt file consist in a list of indices that refer to mesh faces generated using the data from points.txt and faces.txt. Each index indicates the "ownership" of a cell to a mesh face. This format is specially particular, since the data is structured hierarchically with the main goal to apply different properties to each geometry separately.
### Challenges & Solutions

A quite relevant issue was found during the exploration and early development of the GH custom component. In the Rhinoceros-Grasshopper environment meshes can only consist of 3 or 4 vertices. The OpenFOAM mesh face geometry can be described by more than 4 vertices. This initial conflict creates a difference between the amount of mesh faces described in the faces.txt file and the mesh generated in Grasshopper. A quick workaround was implemented to define all mesh faces: triangulate the mesh faces described by more than 4 vertices so they can be generated properly.

### General Takeaway, Skills & Knowledge Acquired

The main knowledge acquired is related to a parser. In addition, inherently learned the Grasshopper component structure from the input, outputs and solver inside the implementation. Additional experience was acquired regarding debugging.

#### Second team meeting

We met to present individual advances in each particular task assigned previously. 

-  Rothe, Chinmay: researched simulation parameters in the OpenFOAM environment through literature review. Presented a research methodologies flowchart to outline his current advances in the project.
- Shen, Rui: mapped the mesh generation structure in OpenFOAM, and proposed a complete timeline for his work in the project. Installed OpenFOAM and run tests.
- Alvarez, Marcelo: development and implementation of GH custom components to read OpenFOAM-generated meshes. Advances consisted in the development of the "Cell from txt" custom GH component. Suggested to continue working on development focusing on the owner.txt and cellZones.txt files from the constant folder.
- Vegas, Gonzalo: presented a timeline for the main MetaFOAM development. During this weeks he will be cleaning and organizing the code, develop a logic to read weather file to input required weather data to the solver, and work on the GH component "checkMesh" to facilitate  testing of meshing.
- Jadhav, Shruti: still looking for a work of her interest.

### Personal Reflection

As a three-credit student for the course, I'll be working in the development of the MetaFOAM grasshopper plugin with the author Gonzalo Vegas. Also, I suggested to take care of the administrative and management of the team's tasks and all issues related to the coordination of the team. Once we met again next week, we'll be sharing our insights and findings in order to continue. 

### Visual Documentation

![imagen](https://github.com/user-attachments/assets/2a102867-fc50-4a16-b3af-de9ba38afbc9)
Figure 1: Mesh from poitns.txt and faces.txt

![imagen](https://github.com/user-attachments/assets/d7077c3d-ca2c-40d0-9d37-8302a00ab0d9)
Figure 2: Cells from owner.txt

![imagen](https://github.com/user-attachments/assets/fb861411-e0d3-42cb-8cc3-c9251c6d080f)
Figure 3: Sample values picked from the cellZones.txt file

---

### Plans for Next Week

Present new advances in the development and implementation of the custom components, aiming to provide the necessary tools as early as possible to the team for enabling the geometry testing.
