### ISSUE TITLE
Week 3_Personal documentation_Marcelo Alvarez

### ISSUE THREAD

**Issue by alvarezdmarch** [VIP-SMUR/24Fa-Microclimate-UMCF#3]
### Overview

- **Week Span:** `[09-09-2024]` to `[09-15-2024]`
### Tasks for This Week

- [x]  Task 1: Study the relationship between owner.txt and neighbour.txt files
- [x]  Task 2: Work on a custom Grasshopper component to read owner.txt and neighbour.txt files correctly, aiming to generate cells.
- [x] Task 3: Keep track of team's current advances and documentation for the course.

##### Task: [Review constant folder] - _(in progress)_

- **Description:** Study and understand the structure of the files and data inside the constant folder prior to simulation. Based on the advances from previous week, the neighbour.txt dataset is required to correctly generate cell geometries.
- **Outcome & Reflection:** Both owner.txt and neighbour.txt files contain indices. The owner.txt file is a list of integers where each index points to the face indices in the faces.txt file, and the value of each integer define the cell that "owns" the face. Neighbors can only be internal faces, so the item count is always smaller than the owners. Each integer in this file refers to the same mesh face, and the value of each data point indicates that the face also belongs to that cell.
### Challenges & Solutions

The main challenge, besides of understanding the structure and the relationship between all files in the constant folder, is the handling in the Rhinoceros - Grasshopper environment. Natively, only mesh faces described by 3 or 4 vertices can exist. Since OpenFOAM mesh faces can be described by more than 4 vertices, we initially triangulated those faces so Grasshopper can render all of them. This would increase or decrease the face count, resulting in differences between the initial length of data and the length of the generated data. The solution so far is to create a single mesh instead of a mesh face, so the mesh is a single item for each mesh face regardless of its vertices count.

Another challenge was more on the technical side. We tried to enhance the definition of the mesh creating a custom class to handle the properties of OpenFOAM meshes directly. This task is still in progress, and will be addressed at the same time of the upcoming tasks for the development of the plugin. Now we have a set of Grasshopper custom components ready to be used by the team member working on meshing exploration.
### General Takeaway, Skills & Knowledge Acquired

These advances translated in acquiring general notions of the meshNGons from Rhinocommon. Although it is not implemented yet in the MetaFOAM due to technical challenges, it could render the mesh faces described by more than 4 vertices so the output could be a lot lighter.

### Visual Documentation

Figure 1: Cells with mesh faces described by more than 4 vertices. The highlighted cell is the first cell in the system.
![Captura de pantalla 2024-09-15 175334](https://github.com/user-attachments/assets/7dd26158-a82d-4b2c-b5bd-bd0c17a0b2fc)

Figure 2: Trees cellZones working.
![Captura de pantalla 2024-09-15 175712](https://github.com/user-attachments/assets/1a67737c-b661-418e-8112-08f445ade404)

---

### Plans for Next Week

Be fully able to retrieve and visualize all data, ideally under more optimized circumstances. The immediate goal is to provide the tool for quick visualization and manipulation for the teammate working on this task.
