### ISSUE TITLE
Week 6_Personal documentation_Marcelo Alvarez

### ISSUE THREAD

**Issue by alvarezdmarch** [VIP-SMUR/24Fa-Microclimate-UMCF#6]
### Overview

- **Week Span:** `[09-30-2024]` to `[10-06-2024]`
### Tasks for This Week

- [x] Task 1: Exploration of tree mesh geometries in a real context case study.
- [x] Task 2: Perform an initial sample of different tree mesh geometries using the ShrinkWrap method in Grasshopper.
- [x] Task 3: Run the checkMesh OpenFOAM function to get initial performance indicators.
##### Task: Checking the mesh quality for tree geometries

- **Description:** In real scenarios we need tradeoff the accuracy of a mesh geometry and its computation times. Also, due to the nature of OpenFOAM polymeshes, simulation may be error-prone to conflictive geometries based on their topology and standard quality parameters to run successfully. The focus of this task is to explore and attempt to find correlations between parameters that the user can manipulate to generate polyMesh geometries. On one side, there is a set of parameters allowing the generation of a ShrinkWrap method in Grasshopper to get a mesh geometry based on an .STL mesh input. On the other side, there are parameters stored in .txt files within OpenFOAM directories, such as meshQualityDict and snappyHexMeshDict.
- **Outcome & Reflection:** The outcomes for this initial stage of exploration consists in a data frame that collects the actual values in the settings of our files and the typical values according to OpenFOAM documentation. We ran a set of 16 subsamples from a Fractional Factorial Design of Experiments since the combinations, acceptable values and results are mostly unknown. 
### Challenges & Solutions

The main challenge is dealing with the potentially large design space that may generate from the combination of all parameters in the system. Currently, we are learning what each parameters does exactly, and how it may impact in the output geometry prior to simulation. Hopefully we could be able to find relevant correlations, determine the importance of each parameter in the system, and be able to control the output geometries to pass the checkMesh algorithm.
### General Takeaway, Skills & Knowledge Acquired

A data modeling approach was needed to conduct the initial study. We were able to execute a Fractional Factorial Design of Experiments to get a subsample of 16 variants from a 450-size data frame.
### Visual Documentation

Figure 1: checkMesh execution.
![Captura de pantalla 2024-10-05 202657](https://github.com/user-attachments/assets/9c74d68c-e797-4c3f-b761-df61983e0088)

Figure 2: Fractional Factorial DoE output
![Captura de pantalla 2024-10-06 193110](https://github.com/user-attachments/assets/25746c7d-b38e-4d9f-8de4-a08c093aa6a8)

Figure
![Captura de pantalla 2024-10-06 193638](https://github.com/user-attachments/assets/f2d15e37-01b7-4c1e-98f5-789a7464dd03)
 3: Key-value dataset

Figure 4: Study in progress
![Captura de pantalla 2024-10-06 193654](https://github.com/user-attachments/assets/1abaebf8-29b7-4661-9fb1-6842b0d5dbef)

Figure 5: checkMesh checking example
![Captura de pantalla 2024-10-06 193702](https://github.com/user-attachments/assets/ed7b19ce-9991-46ee-a071-8c0c5c53cb9b)

---
### Plans for Next Week

Analyze the obtained data to find relevant observations and correlations. Visualize the mesh outputs and identify potential issues. Automate the checking process to handle larger datasets.
