### ISSUE TITLE
Week 7_Personal documentation_Marcelo Alvarez

### ISSUE THREAD

**Issue by alvarezdmarch** [VIP-SMUR/24Fa-Microclimate-UMCF#7]
### Overview

- **Week Span:** `[10-07-2024]` to `[10-13-2024]`
### Tasks for This Week

- [x] Task 1: Explore meshing quality parameters with the ShrinkWrap grasshopper method.
- [x] Task 2: Develop a Grasshopper custom component to read the log file generated by checkMesh.
- [x] Task 3: Obtain and document relevant information from initial exploration.
##### Task: Checking the mesh quality for tree geometries

- **Description:** To continue with the task of checking the mesh quality for the tree geometries prior to simulation, we developed a Grasshopper custom component that allows us to read the .txt file containing the log of the checkMesh process. This is useful to extract and transform relevant data in a more automated fashion. In this instance, we implemented a Grasshopper script able to write the data frame in a .xlsx file for further management. The study was conducted with a Fractional Design of Experiments (DoE) with 16 samples. This small subset allows to run and get relevant data quickly enough to start the exploration.
- **Outcome & Reflection:** The sample size was not sufficient. Trying to get data correlation based on statistical methods was not as expected. However, we can conclude that we must also consider manipulating parameters for the snappyHexMesh method along with the ShrinkWrap method.
### Challenges & Solutions

One challenge is to expand the data set using a full Factorial Design of Experiments, with more predictors for a better response. Increasing the bounds of the ranges for the parameters is key for further exploration. Also, being able to write meshes and run checkMesh processes automatically would align well with a systematic approach for this task.
### General Takeaway, Skills & Knowledge Acquired

This is a good scenario to put statistical knowledge into practice. Since the output is raw data, we can directly try to measure mesh quality statistics with the right approach. 
### Visual Documentation

Figure 1: Initial data subset results (most columns are omitted to show most relevant information).
![Captura de pantalla 2024-10-14 210018](https://github.com/user-attachments/assets/493b78a5-cf11-40fb-9201-e498ff9a59c5)

Figure 2: MeshQual custom component.
![meshqualread](https://github.com/user-attachments/assets/7f9b5613-e45d-4a9f-a737-c46a364a7ac8)

Figure 3: Case study 1.
![01](https://github.com/user-attachments/assets/91405689-1ec2-48dd-9f61-031c9b87a269)

Figure 4: Case study 2.
![02](https://github.com/user-attachments/assets/d9bdd1b4-9aa2-4354-a998-a64b5778bbab)

Figure 5: Case study 3.
![03](https://github.com/user-attachments/assets/4e1c78db-127f-4960-9813-906d1a978511)

Figure 6: Case study 4.
![04](https://github.com/user-attachments/assets/55bdd9f3-cb79-40b4-adfc-259fc0ce0f70)

Figure 7: Case study 5.
![05](https://github.com/user-attachments/assets/3d657676-6dbf-4bfd-aa75-33d06b0ac90a)

Figure 8: Case study 6.
![06](https://github.com/user-attachments/assets/c9582630-2c01-4568-bce3-a654a2c6d6e1)

Figure 9: Case study 7.
![07](https://github.com/user-attachments/assets/291aa979-8d41-4372-b57b-2136f82c8caf)

Figure 10: Case study 8.
![08](https://github.com/user-attachments/assets/e98b4532-6c64-49da-9e93-a7f7ee8b9541)

Figure 11: Case study 9.
![09](https://github.com/user-attachments/assets/7730a58c-05e2-4992-86d4-69bcda37e8a4)

Figure 12: Case study 10.
![10](https://github.com/user-attachments/assets/11eaef11-12df-4151-8b21-3fdf65c0564d)

Figure 13: Case study 11.
![11](https://github.com/user-attachments/assets/3bda7e34-4eed-44ea-831f-256a96e3aa54)

Figure 14: Case study 12.
![12](https://github.com/user-attachments/assets/289d41c9-cd0e-4576-9c84-75527509b0fe)

Figure 15: Case study 13.
![13](https://github.com/user-attachments/assets/e7266495-7de7-457e-8b4a-ac7888ebdc86)

Figure 16: Case study 14.
![14](https://github.com/user-attachments/assets/ef5e5b4d-0979-42c8-9eea-91e8eac47c18)

Figure 17: Case study 15.
![15](https://github.com/user-attachments/assets/fb0a6c91-3b78-4aee-967c-b39f4995e97d)

Figure 18: Case study 16.
![16](https://github.com/user-attachments/assets/64d53acc-4528-4b95-9a21-1b834475fb69)

---
### Plans for Next Week

This task will be on hold to focus on running simulations, identify potential errors and solve them systematically. We will explore and solve issues related to the urbanMicroClimateFoam solver. The ideal is to be able to run a simulation successfully along with data visualization. Once the simulation is working in most cases, we will proceed to run the stadium real-scenario case study.
