### ISSUE TITLE
Week 8_Personal documentation_Marcelo Alvarez

### ISSUE THREAD

**Issue by alvarezdmarch** [VIP-SMUR/24Fa-Microclimate-UMCF#8]
### Overview

- **Week Span:** `[10-14-2024]` to `[10-20-2024]`
### Tasks for This Week

- [x] Task 1: Explore and iterate over geometry generation for troubleshooting.
- [x] Task 2: Understand each type of error and its breakpoints.
- [ ] Task 3: Determine a consistent setting to start and finish a simulation successfully.
##### Task: Simulation error prevention through geometry and dictionary configuration

- **Description:** The main goal is to determine a consistent configuration of parameters and geometry definition for the vegetation region that runs without crashing. Since we already manipulated parameters in the Grasshopper's meshing method, this task focuses on manipulating files in each OpenFOAM case. We gather all different type of errors in the simulation to understand what failed and solve the issue in the process.
- **Outcome & Reflection:** After the exploration process, we identified and tried to understand what is the meaning of each exception in the execution of the solver. We have a couple of hypotheses for the errors, but need to be further tested.
### Challenges & Solutions

The most relevant challenge is to address the different errors knowing exactly how to. With a specific combination of parameters and settings the simulation would run, but changing a single value we got different solution exceptions with no real understanding of what went wrong. The proposed solution is to find exactly the breakpoint in the simulation based on the mesh settings. We think that the amount of cells in the domain may be tied to the hardware capabilities, since meshes are not generating errors according to the checkMesh command.
### General Takeaway, Skills & Knowledge Acquired

We acquired more knowledge about OpenFOAM solution exceptions and the different steps that would lead to a crash. The most recurrent error is related to sigSegv, related to a invalid memory location access.
### Visual Documentation

Figure 1: sigSegv error log.
![errro with more simplified geometry](https://github.com/user-attachments/assets/a6565ffd-add9-412d-92e4-186b1bf587b4)

Figure 2: Case worked.
![Captura de pantalla 2024-10-20 225425](https://github.com/user-attachments/assets/655cecf6-ccb0-4a20-aded-546e5aa735d7)

Figure 3: Simulation runs successfully if the domain is small enough and trees are not merged together?
![Captura de pantalla 2024-10-20 145232](https://github.com/user-attachments/assets/b012a787-0e8e-4761-b4e4-f0fd0c7c8e4b)

Figure 4: Simulation running.
![Captura de pantalla 2024-10-20 145136](https://github.com/user-attachments/assets/1046113e-a47a-40c1-a714-55544c34764e)

Figure 5: Should vegetation geometry have edges/features?
![Captura de pantalla 2024-10-16 142654](https://github.com/user-attachments/assets/f90c6787-9de6-4bc9-95b0-2cc0a86ab17d)

Figure 6: Mismatch between air cells and vegetation cells?
![Captura de pantalla 2024-10-18 133338](https://github.com/user-attachments/assets/8f35df01-2f99-46e2-837a-4889bb874437)

---
### Plans for Next Week

Solve task 3 and find a breakpoint to consistently get errors and run simulation successfully.
